=== api-evangelist/palo-alto-networks/json-schema/prisma-cloud-mssp-api-update-managed-tenant-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "UpdateManagedTenantRequest",
  "description": "UpdateManagedTenantRequest schema from Prisma Cloud: Managed Security Service Provider (MSSP)",
  "$id": "https://raw.githubusercontent.com/api-evangelist/palo-alto-networks/refs/heads/main/json-schema/prisma-cloud-mssp-api-update-managed-tenant-request-schema.json",
  "type": "object",
  "properties": {
    "tenantGroupId": {
      "type": "string",
      "format": "uuid"
    },
    "companyName": {
      "maxLength": 63,
      "minLength": 3,
      "type": "string"
    },
    "licenseInfo": {
      "required": [
        "allocatedCredits",
        "licensePoolId"
      ],
      "type": "object",
      "properties": {
        "licensePoolId": {
          "type": "string"
        },
        "allocatedCredits": {
          "minimum": 1,
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "modules": {
      "type": "array",
      "items": {
        "required": [
          "enabled",
          "featureName"
        ],
        "type": "object",
        "properties": {
          "featureName": {
            "pattern": "iam-security",
            "type": "string"
          },
          "enabled": {
            "type": "boolean"
          },
          "additionalData": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            }
          }
        }
      }
    }
  }
}

=== api-evangelist/palo-alto-networks/examples/prisma-cloud-mssp-api-update-managed-tenant-request-example.json
{
  "tenantGroupId": "6f0c2c4c-fcf5-45b1-b4fa-3421b9456e59",
  "companyName": "Remote Policy 88",
  "licenseInfo": {
    "licensePoolId": "318600",
    "allocatedCredits": 599
  },
  "modules": [
    {
      "featureName": "Development Firewall 95",
      "enabled": true,
      "additionalData": {}
    },
    {
      "featureName": "Corporate Scanner 41",
      "enabled": true,
      "additionalData": {}
    }
  ]
}
