=== api-evangelist/palo-alto-networks/json-schema/prisma-cloud-mssp-api-managed-tenant-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ManagedTenantResponse",
  "description": "ManagedTenantResponse schema from Prisma Cloud: Managed Security Service Provider (MSSP)",
  "$id": "https://raw.githubusercontent.com/api-evangelist/palo-alto-networks/refs/heads/main/json-schema/prisma-cloud-mssp-api-managed-tenant-response-schema.json",
  "type": "object",
  "properties": {
    "prismaId": {
      "type": "string"
    },
    "externalTenantId": {
      "type": "string"
    },
    "customerName": {
      "type": "string"
    },
    "companyName": {
      "type": "string"
    },
    "status": {
      "type": "string",
      "enum": [
        "ACTIVE",
        "PROVISIONING",
        "UPDATING",
        "DELETING",
        "DELETED",
        "OFFBOARDING",
        "ERRORED"
      ]
    },
    "isSynthetic": {
      "type": "boolean"
    },
    "wasMigrated": {
      "type": "boolean"
    },
    "msspId": {
      "type": "string"
    },
    "tenantGroupId": {
      "type": "string",
      "format": "uuid"
    },
    "planType": {
      "type": "string",
      "enum": [
        "RS_STANDARD",
        "RS_FOUNDATION",
        "RS_ADVANCED"
      ]
    },
    "contactInfo": {
      "required": [
        "email",
        "firstName",
        "lastName"
      ],
      "type": "object",
      "properties": {
        "firstName": {
          "maxLength": 63,
          "minLength": 1,
          "type": "string"
        },
        "lastName": {
          "maxLength": 63,
          "minLength": 1,
          "type": "string"
        },
        "email": {
          "maxLength": 128,
          "minLength": 1,
          "type": "string"
        }
      }
    },
    "stack": {
      "type": "string"
    },
    "region": {
      "type": "string"
    },
    "baseApiUrl": {
      "type": "string"
    },
    "tenantLicense": {
      "type": "object",
      "properties": {
        "tenantLicenseId": {
          "type": "string"
        },
        "serialNumber": {
          "type": "string"
        },
        "licensePoolId": {
          "type": "string"
        },
        "allocatedCredits": {
          "type": "integer",
          "format": "int32"
        },
        "startDate": {
          "type": "integer",
          "format": "int64"
        },
        "endDate": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "createdBy": {
      "type": "string"
    },
    "createdAt": {
      "type": "integer",
      "format": "int64"
    },
    "modules": {
      "type": "array",
      "items": {
        "required": [
          "feature_name"
        ],
        "type": "object",
        "properties": {
          "feature_name": {
            "type": "string"
          },
          "enabled": {
            "type": "boolean"
          },
          "billing_type": {
            "type": "string",
            "enum": [
              "TRIAL",
              "BUY"
            ]
          },
          "state": {
            "type": "string",
            "enum": [
              "PROVISION_STARTED",
              "PROVISION_SUCCESSFUL",
              "PROVISION_FAILED"
            ]
          },
          "additional_data": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            }
          }
        }
      }
    },
    "erroredBy": {
      "type": "string",
      "format": "uuid"
    }
  }
}

=== api-evangelist/palo-alto-networks/examples/prisma-cloud-mssp-api-managed-tenant-response-example.json
{
  "prismaId": "706897",
  "externalTenantId": "962486",
  "customerName": "Remote Scanner 64",
  "companyName": "Corporate Scanner 95",
  "status": "DELETED",
  "isSynthetic": false,
  "wasMigrated": true,
  "msspId": "224867",
  "tenantGroupId": "15882d79-d75d-4566-b5c6-b1d080ff0567",
  "planType": "RS_ADVANCED",
  "contactInfo": {
    "firstName": "Remote Scanner 24",
    "lastName": "Corporate Gateway 17",
    "email": "security-ops@example.com"
  },
  "stack": "example-stack",
  "region": "eu-west-1",
  "baseApiUrl": "example-baseApiUrl",
  "tenantLicense": {
    "tenantLicenseId": "569945",
    "serialNumber": "example-serialNumber",
    "licensePoolId": "959709",
    "allocatedCredits": 589,
    "startDate": 199,
    "endDate": 17
  },
  "createdBy": "example-createdBy",
  "createdAt": 18,
  "modules": [
    {
      "feature_name": "Secondary Connector 60",
      "enabled": true,
      "billing_type": "TRIAL",
      "state": "PROVISION_SUCCESSFUL",
      "additional_data": {}
    },
    {
      "feature_name": "Remote Scanner 77",
      "enabled": false,
      "billing_type": "BUY",
      "state": "PROVISION_SUCCESSFUL",
      "additional_data": {}
    },
    {
      "feature_name": "Production Firewall 88",
      "enabled": true,
      "billing_type": "BUY",
      "state": "PROVISION_SUCCESSFUL",
      "additional_data": {}
    }
  ],
  "erroredBy": "f89798a8-cd56-4eea-b118-9f05c81cd7b2"
}
