=== api-evangelist/palo-alto-networks/json-schema/prisma-cloud-mssp-api-operation-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "OperationResponse",
  "description": "OperationResponse schema from Prisma Cloud: Managed Security Service Provider (MSSP)",
  "$id": "https://raw.githubusercontent.com/api-evangelist/palo-alto-networks/refs/heads/main/json-schema/prisma-cloud-mssp-api-operation-response-schema.json",
  "type": "object",
  "properties": {
    "requestId": {
      "type": "string",
      "format": "uuid"
    },
    "msspId": {
      "type": "string",
      "format": "uuid"
    },
    "operationType": {
      "type": "string",
      "enum": [
        "MESSAGE_FAN_OUT",
        "ORCHESTRATOR_REQUEST"
      ]
    },
    "operationName": {
      "type": "string",
      "enum": [
        "PROVISION_TENANT",
        "UPDATE_TENANT",
        "DELETE_TENANT",
        "OFFBOARD_TENANT",
        "REPLICATE_ACTION",
        "CREATE_USER",
        "UPDATE_USER",
        "DELETE_USER",
        "POLICY_MAP",
        "POLICY_UNMAP",
        "SYNC_POLICIES"
      ]
    },
    "operationDescription": {
      "type": "string"
    },
    "status": {
      "type": "string",
      "enum": [
        "IN_PROGRESS",
        "SUCCESS",
        "FAILURE"
      ]
    },
    "tenantChanges": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "tenantChangeId": {
            "type": "string",
            "format": "uuid"
          },
          "externalTenantId": {
            "type": "string"
          },
          "tenantPrismaId": {
            "type": "string"
          },
          "status": {
            "type": "string",
            "enum": [
              "IN_PROGRESS",
              "SUCCESS",
              "FAILURE"
            ]
          },
          "updatedAt": {
            "type": "integer",
            "format": "int64"
          }
        }
      }
    },
    "startedBy": {
      "type": "string"
    },
    "startedAt": {
      "type": "integer",
      "format": "int64"
    },
    "updatedAt": {
      "type": "integer",
      "format": "int64"
    },
    "isRetryable": {
      "type": "boolean"
    },
    "retryOf": {
      "type": "string",
      "format": "uuid"
    },
    "retriedBy": {
      "type": "string",
      "format": "uuid"
    }
  }
}

=== api-evangelist/palo-alto-networks/examples/prisma-cloud-mssp-api-operation-response-example.json
{
  "requestId": "191f35bc-566b-4dee-a278-396c4b194e70",
  "msspId": "95ca43cd-d79e-4363-9c7b-29afdc269dac",
  "operationType": "ORCHESTRATOR_REQUEST",
  "operationName": "DELETE_TENANT",
  "operationDescription": "Policy incident monitoring activity firewall policy rule suspicious monitoring incident policy activity suspicious blocked.",
  "status": "FAILURE",
  "tenantChanges": [
    {
      "tenantChangeId": "83fddca5-19d5-4d80-97a9-53e3dcd2bc26",
      "externalTenantId": "587465",
      "tenantPrismaId": "481562",
      "status": "FAILURE",
      "updatedAt": 609
    },
    {
      "tenantChangeId": "7097a803-3567-45f5-889f-792323fbbfd4",
      "externalTenantId": "887467",
      "tenantPrismaId": "199225",
      "status": "SUCCESS",
      "updatedAt": 139
    }
  ],
  "startedBy": "example-startedBy",
  "startedAt": 461,
  "updatedAt": 568,
  "isRetryable": false,
  "retryOf": "0509f974-309d-4806-a150-aa662c2ef2d6",
  "retriedBy": "e806c758-5370-4a75-ac5c-8f8ffa67ef1e"
}
